version: "3.9"

services:
  db:
    image: mysql:8.0.32
    command: --default-authentivation-plugin=mysql_native-password
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword1234
      MYSQL_DATABASE: test
      MYSQL_USER: ishow
      MYSQL_PASSWORD: P@ssword1234
    volumes:
      - ./init-db:/docker-entrypoint-initdb.db
      - ./db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - mynetwork
  api:
    build: .
    environment:
      PORT: 5000
      DB_HOST: db
      DB_USER: ishow
      DB_PASSWORD: ssword1234
      DB_NAME: test
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge