version: "3.9"

services:
  db:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword1234
      MYSQL_DATABASE: test
      MYSQL_USER: ishow
      MYSQL_PASSWORD: P@ssword1234
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - mynetwork
  api:
    build: .
    environment:
      PORT: 5000
      DB_HOST: db
      DB_USER: ishow
      DB_PASSWORD: P@ssword1234
      DB_DATABASE: test
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - mynetwork
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  mynetwork:
    driver: bridge