version: "3.9"

services:
  db:
   image: mysql:8.0.32
   command: --default-authentication-plugin=mysql_native_password
   environment:
     MYSQL_ROOT_PASSWORD: P@ssw0rd1234
     MYSQL_DATABASE: test
     MYSQL_USER: root
     MYSQL_PASSWORD: P@ssw0rd1234
   volumes:
     - ./init-db:/docker-entrypoint-initdb.d
     - ./db-data:/var/lib/mysql
   ports:
     - '3306:3306'
   networks:
     - mynetwork
  api:
   build: .
   environment:
     DB_HOST: db
     DB_USER: root
     DB_PASSWORD: P@ssw0rd1234
     DB_DATABASE: test
     PORT: 5000
   ports:
     - '5000:5000'
   depends_on:
     - db
   networks:
     - mynetwork

networks:
  mynetwork:
    driver: bridge